apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./victoria-metrics
  - ./metrics-server

labels:
  - pairs:
      app.kubernetes.io/component: monitoring
      toolkit.fluxcd.io/tenant: infra
