apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./prometheus-operator-crds

labels:
  - pairs:
      app.kubernetes.io/component: crds
      toolkit.fluxcd.io/tenant: infra
