apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./victoria-metrics.yaml
  - ./update.yaml

configMapGenerator:
  - name: flux-kube-state-metrics-config
    namespace: flux-system
    files:
      - values.yaml=kube-state-metrics-config.yaml

configurations:
  - kustomizeconfig.yaml
