---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-controllers
  namespace: flux-system
  labels:
    app.kubernetes.io/component: ingress
spec:
  dependsOn:
    - name: crds-controllers
    - name: tls-controllers
  serviceAccountName: flux-infra
  interval: 1m
  retryInterval: 30s
  timeout: 30s
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
  path: components/ingress/controllers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-configs
  namespace: flux-system
  labels:
    app.kubernetes.io/component: ingress
spec:
  dependsOn:
    - name: ingress-controllers
    - name: ipam-configs
  serviceAccountName: flux-infra
  interval: 1m
  retryInterval: 30s
  timeout: 30s
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
  path: components/ingress/configs
