---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: private-gateway-issuer
  namespace: envoy-gateway-system
spec:
  acme:
    email: guillaume@cleroux.dev
    privateKeySecretRef:
      name: private-gateway-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - selector:
          dnsZones:
            - ${EXTERNAL_DOMAIN}
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: private-gateway-cert
  namespace: envoy-gateway-system
spec:
  issuerRef:
    name: private-gateway-issuer
    kind: Issuer
  dnsNames:
    - "*.${EXTERNAL_DOMAIN}"
  secretName: private-gateway-tls
