apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - ./l2advertisement.yaml
  - ./ip-pool.yaml

labels:
  - pairs:
      app.kubernetes.io/component: ipam
      toolkit.fluxcd.io/tenant: infra
