---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./openebs.yaml
  - ./update.yaml

labels:
  - pairs:
      app.kubernetes.io/component: storage
      toolkit.fluxcd.io/tenant: infra
