apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ./agent.yaml
  - ./blocky.yaml
  - ./unbound.yaml

labels:
  - pairs:
      scrape: calcifer-external
