apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: node-exporter-metrics
spec:
  jobName: node-exporter_service
  targetEndpoints:
    - targets:
        - "calcifer.lan:9100"
      path: /metrics
      interval: 15s
