apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./dragonflydb
  - ./postgres

labels:
  - pairs:
      app.kubernetes.io/component: database
      toolkit.fluxcd.io/tenant: infra
