apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./metallb.yaml

labels:
  - pairs:
      app.kubernetes.io/component: ipam
      toolkit.fluxcd.io/tenant: infra
