apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ./hosts/calcifer
  - ./podmonitor.yaml

configMapGenerator:
  - name: flux-grafana-dashboards
    files:
      - ./dashboards/control-plane.json
      - ./dashboards/cluster.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
      annotations:
        grafana_folder: "Flux"
        kustomize.toolkit.fluxcd.io/substitute: disabled

  - name: networking-grafana-dashboards
    files:
      - ./dashboards/unbound.json
      - ./dashboards/blocky-grafana.json
      - ./dashboards/dnsmasq.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
      annotations:
        grafana_folder: "Networking"
        kustomize.toolkit.fluxcd.io/substitute: disabled
